import type { MBTIType } from '@/types';

export interface SceneConfig {
  type: MBTIType;
  name: string;
  nickname: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  particleColor: string;
  backgroundColor: string;
  description: string;
  theme: string;
}

export const SCENE_CONFIGS: Record<MBTIType, SceneConfig> = {
  INTJ: {
    type: 'INTJ',
    name: 'Architect',
    nickname: 'The Mastermind',
    primaryColor: '#1e1b4b',
    secondaryColor: '#4338ca',
    accentColor: '#818cf8',
    particleColor: '#c7d2fe',
    backgroundColor: '#0f0d1a',
    description: 'Imaginative and strategic thinkers with a plan for everything.',
    theme: 'cosmic-library',
  },
  INTP: {
    type: 'INTP',
    name: 'Logician',
    nickname: 'The Thinker',
    primaryColor: '#083344',
    secondaryColor: '#0e7490',
    accentColor: '#22d3ee',
    particleColor: '#a5f3fc',
    backgroundColor: '#042f2e',
    description: 'Innovative inventors with an unquenchable thirst for knowledge.',
    theme: 'abstract-lab',
  },
  ENTJ: {
    type: 'ENTJ',
    name: 'Commander',
    nickname: 'The Executive',
    primaryColor: '#422006',
    secondaryColor: '#b45309',
    accentColor: '#fbbf24',
    particleColor: '#fef3c7',
    backgroundColor: '#1c1917',
    description: 'Bold, imaginative and strong-willed leaders.',
    theme: 'command-center',
  },
  ENTP: {
    type: 'ENTP',
    name: 'Debater',
    nickname: 'The Visionary',
    primaryColor: '#3f3f46',
    secondaryColor: '#f97316',
    accentColor: '#fb923c',
    particleColor: '#fed7aa',
    backgroundColor: '#18181b',
    description: 'Smart and curious thinkers who love intellectual challenges.',
    theme: 'idea-storm',
  },
  INFJ: {
    type: 'INFJ',
    name: 'Advocate',
    nickname: 'The Counselor',
    primaryColor: '#134e4a',
    secondaryColor: '#0d9488',
    accentColor: '#5eead4',
    particleColor: '#ccfbf1',
    backgroundColor: '#042f2e',
    description: 'Quiet and mystical, yet inspiring and tireless idealists.',
    theme: 'mystic-garden',
  },
  INFP: {
    type: 'INFP',
    name: 'Mediator',
    nickname: 'The Healer',
    primaryColor: '#4c1d95',
    secondaryColor: '#7c3aed',
    accentColor: '#a78bfa',
    particleColor: '#ddd6fe',
    backgroundColor: '#1e1b2e',
    description: 'Poetic, kind and altruistic people, always eager to help.',
    theme: 'aurora-dreams',
  },
  ENFJ: {
    type: 'ENFJ',
    name: 'Protagonist',
    nickname: 'The Teacher',
    primaryColor: '#7c2d12',
    secondaryColor: '#ea580c',
    accentColor: '#fdba74',
    particleColor: '#ffedd5',
    backgroundColor: '#1c1917',
    description: 'Charismatic and inspiring leaders who mesmerize their listeners.',
    theme: 'gathering-light',
  },
  ENFP: {
    type: 'ENFP',
    name: 'Campaigner',
    nickname: 'The Champion',
    primaryColor: '#831843',
    secondaryColor: '#db2777',
    accentColor: '#f472b6',
    particleColor: '#fbcfe8',
    backgroundColor: '#1f1d2b',
    description: 'Enthusiastic, creative and sociable free spirits.',
    theme: 'celebration',
  },
  ISTJ: {
    type: 'ISTJ',
    name: 'Logistician',
    nickname: 'The Inspector',
    primaryColor: '#1e3a5f',
    secondaryColor: '#475569',
    accentColor: '#94a3b8',
    particleColor: '#e2e8f0',
    backgroundColor: '#0f172a',
    description: 'Practical and fact-minded individuals whose reliability cannot be doubted.',
    theme: 'clockwork',
  },
  ISFJ: {
    type: 'ISFJ',
    name: 'Defender',
    nickname: 'The Protector',
    primaryColor: '#365314',
    secondaryColor: '#65a30d',
    accentColor: '#a3e635',
    particleColor: '#ecfccb',
    backgroundColor: '#14532d',
    description: 'Very dedicated and warm protectors, always ready to defend loved ones.',
    theme: 'cozy-sanctuary',
  },
  ESTJ: {
    type: 'ESTJ',
    name: 'Executive',
    nickname: 'The Supervisor',
    primaryColor: '#1e293b',
    secondaryColor: '#64748b',
    accentColor: '#f8fafc',
    particleColor: '#e2e8f0',
    backgroundColor: '#0f172a',
    description: 'Excellent administrators, unsurpassed at managing things or people.',
    theme: 'monument',
  },
  ESFJ: {
    type: 'ESFJ',
    name: 'Consul',
    nickname: 'The Provider',
    primaryColor: '#be185d',
    secondaryColor: '#f472b6',
    accentColor: '#fce7f3',
    particleColor: '#fdf2f8',
    backgroundColor: '#1f1d2b',
    description: 'Extraordinarily caring, social and popular people.',
    theme: 'community',
  },
  ISTP: {
    type: 'ISTP',
    name: 'Virtuoso',
    nickname: 'The Craftsman',
    primaryColor: '#27272a',
    secondaryColor: '#52525b',
    accentColor: '#a1a1aa',
    particleColor: '#e4e4e7',
    backgroundColor: '#18181b',
    description: 'Bold and practical experimenters, masters of all kinds of tools.',
    theme: 'workshop',
  },
  ISFP: {
    type: 'ISFP',
    name: 'Adventurer',
    nickname: 'The Composer',
    primaryColor: '#5b21b6',
    secondaryColor: '#8b5cf6',
    accentColor: '#c4b5fd',
    particleColor: '#ede9fe',
    backgroundColor: '#1e1b2e',
    description: 'Flexible and charming artists, always ready to explore.',
    theme: 'art-studio',
  },
  ESTP: {
    type: 'ESTP',
    name: 'Entrepreneur',
    nickname: 'The Dynamo',
    primaryColor: '#7f1d1d',
    secondaryColor: '#dc2626',
    accentColor: '#f87171',
    particleColor: '#fecaca',
    backgroundColor: '#1c1917',
    description: 'Smart, energetic people who truly enjoy living on the edge.',
    theme: 'arena',
  },
  ESFP: {
    type: 'ESFP',
    name: 'Entertainer',
    nickname: 'The Performer',
    primaryColor: '#c026d3',
    secondaryColor: '#e879f9',
    accentColor: '#f0abfc',
    particleColor: '#fae8ff',
    backgroundColor: '#1f1d2e',
    description: 'Spontaneous, energetic and enthusiastic people.',
    theme: 'festival',
  },
};
